### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by MiguelAngelCollado** [MiguelAngelCollado/habpref#1]

**Comment by ibartomeus** [comment]
Me encanta que empiezes a usar issues :D Aunque es es poco descriptivo.

**Comment by MiguelAngelCollado** [comment]
Si te han notificado algo, es que he estado toqueteando github (el cual me
resulta poco intuitivo), para intentar simplemente crear una carpeta para
meterte los scripts ya bien ordenaditos y en otra carpeta los dataframes,
pero he desistido por hoy.

2015-09-11 10:24 GMT+02:00 Ignasi Bartomeus notifications@github.com:
